#include<bits/stdc++.h>
#include<conio.h>
#include<windows.h>
using namespace std;
string ver="1.5.0";
string type="¦Â";
string date="20220719";
string expire="20230719";
vector<string> words={"ABACK","ABAFT","ABASE","ABASH","ABATE","ABBEY","ABBOT","ABEAM","ABHOR","ABIDE","ABODE","ABORT","ABOUT","ABOVE","ABUSE","ABUZZ","ABYSS","ACORN","ACRES","ACRID","ACTOR","ACUTE","ADAGE","ADAPT","ADDER","ADDLE","ADEPT","ADIEU","ADIOS","ADMAN","ADMIT","ADMIX","ADOBE","ADOPT","ADORE","ADORN","ADULT","AEGIS","AERIE","AFFIX","AFIRE","AFOOT","AFOUL","AFTER","AGAIN","AGAPE","AGATE","AGAVE","AGENT","AGGRO","AGILE","AGING","AGLOW","AGONY","AGREE","AHEAD","AIDED","AIRED","AISLE","ALACK","ALARM","ALBUM","ALDER","ALERT","ALGAE","ALGAL","ALIAS","ALIBI","ALIEN","ALIGN","ALIKE","ALIVE","ALKYD","ALLAY","ALLEY","ALLOT","ALLOW","ALLOY","ALOES","ALOFT","ALOHA","ALONE","ALONG","ALOOF","ALOUD","ALPHA","ALTAR","ALTER","AMASS","AMAZE","AMBER","AMBIT","AMBLE","AMEND","AMIDE","AMIGO","AMINE","AMINO","AMISS","AMITY","AMONG","AMOUR","AMPLE","AMPLY","AMUSE","ANENT","ANGEL","ANGER","ANGLE","ANGRY","ANGST","ANION","ANISE","ANKLE","ANNEX","ANNOY","ANNUL","ANODE","ANTIC","ANTSY","ANVIL","AORTA","APACE","APART","APHID","APISH","APNEA","APPLE","APPLY","APRIL","APRON","APTLY","ARBOR","ARCED","ARDOR","AREAL","ARENA","ARGON","ARGOT","ARGUE","ARISE","ARMED","ARMOR","AROMA","ARRAS","ARRAY","ARROW","ARSON","ASCII","ASCOT","ASHEN","ASIDE","ASKEW","ASPEN","ASPIC","ASSAY","ASSET","ASTER","ASTIR","ATILT","ATLAS","ATOLL","ATONE","ATTAR","ATTIC","AUDIO","AUDIT","AUGER","AUGHT","AUGUR","AURAL","AURIC","AUXIN","AVAIL","AVAST","AVERT","AVIAN","AVOID","AWAIT","AWAKE","AWARD","AWARE","AWASH","AWFUL","AWING","AXIAL","AXIOM","AZURE","BABEL","BACCY","BACON","BADGE","BADLY","BAGEL","BAGGY","BAIRN","BAIZE","BAKED","BAKER","BALDY","BALKY","BALLY","BALMY","BALSA","BANAL","BANDY","BANJO","BANNS","BARED","BARGE","BARMY","BARON","BASAL","BASED","BASIC","BASIL","BASIN","BASIS","BASSO","BASTE","BATCH","BATED","BATHE","BATIK","BATON","BATTY","BAULK","BAWDY","BAYOU","BEACH","BEADS","BEADY","BEARD","BEAST","BEATS","BEAUT","BEBOP","BEDIM","BEECH","BEEFY","BEERY","BEFIT","BEFOG","BEGET","BEGIN","BEGUM","BEIGE","BEING","BELAY","BELCH","BELIE","BELLE","BELLY","BELOW","BENCH","BENDS","BERET","BERRY","BERTH","BERYL","BESET","BESOM","BETEL","BEVEL","BEZEL","BIBLE","BIDDY","BIDET","BIGHT","BIGOT","BIJOU","BILGE","BILLY","BINGE","BINGO","BIOTA","BIPED","BIRCH","BIRTH","BISON","BITER","BITTY","BLACK","BLADE","BLAHS","BLAME","BLAND","BLANK","BLARE","BLASE","BLAST","BLAZE","BLEAK","BLEAR","BLEAT","BLEED","BLEEP","BLEND","BLESS","BLIMP","BLIND","BLINI","BLINK","BLISS","BLITZ","BLOAT","BLOCK","BLOKE","BLOND","BLOOD","BLOOM","BLOWN","BLOWY","BLUES","BLUFF","BLUNT","BLURB","BLURT","BLUSH","BOARD","BOAST","BOBBY","BOFFO","BOGEY","BOGGY","BOGUS","BOLUS","BONCE","BONES","BONGO","BONNY","BONUS","BOOBY","BOOST","BOOTH","BOOTY","BOOZE","BOOZY","BORAX","BORED","BORER","BORON","BOSOM","BOSON","BOSSY","BOTCH","BOUGH","BOUND","BOWED","BOWEL","BOWER","BOWLS","BOXED","BOXER","BRACE","BRACT","BRAID","BRAIN","BRAKE","BRAND","BRASH","BRASS","BRAVE","BRAVO","BRAWL","BRAWN","BRAZE","BREAD","BREAK","BREAM","BREED","BREVE","BRIBE","BRICK","BRIDE","BRIEF","BRIER","BRILL","BRINE","BRING","BRINK","BRINY","BRISK","BROAD","BROIL","BROKE","BRONC","BROOD","BROOK","BROOM","BROTH","BROWN","BRUIN","BRUIT","BRUNT","BRUSH","BRUTE","BUDDY","BUDGE","BUGGY","BUGLE","BUILD","BUILT","BULGE","BULGY","BULKY","BULLY","BUMPY","BUNCH","BUNNY","BURGH","BURLY","BURNT","BURRO","BURSA","BURST","BUSBY","BUSHY","BUSTY","BUTTE","BUTTY","BUXOM","BUYER","BYLAW","BYWAY","CABAL","CABER","CABIN","CABLE","CACAO","CACHE","CADDY","CADET","CADGE","CADRE","CAGEY","CAIRN","CALLA","CALVE","CALYX","CAMEL","CAMEO","CAMPY","CANAL","CANDY","CANNY","CANOE","CANON","CANTO","CAPER","CAPON","CARAT","CARDS","CARET","CARGO","CAROB","CAROL","CAROM","CARRY","CARVE","CASED","CASTE","CATCH","CATER","CATTY","CAULK","CAUSE","CAVIL","CEASE","CECAL","CECUM","CEDAR","CELLO","CHAFE","CHAFF","CHAIN","CHAIR","CHALK","CHAMP","CHANT","CHAOS","CHARD","CHARM","CHART","CHARY","CHASE","CHASM","CHEAP","CHEAT","CHECK","CHEEK","CHEEP","CHEER","CHERT","CHESS","CHEST","CHEWY","CHICK","CHIDE","CHIEF","CHILD","CHILI","CHILL","CHIME","CHIMP","CHINA","CHINE","CHINO","CHIPS","CHIRP","CHIVE","CHOCK","CHOIR","CHOKE","CHOMP","CHORD","CHORE","CHUCK","CHUFF","CHUMP","CHUNK","CHURL","CHURN","CHUTE","CHYME","CIDER","CIGAR","CINCH","CIRCA","CISSY","CIVET","CIVIC","CIVIL","CLACK","CLAIM","CLAMP","CLAMS","CLANG","CLANK","CLASH","CLASP","CLASS","CLEAN","CLEAR","CLEAT","CLEFT","CLERK","CLEWS","CLICK","CLIFF","CLIMB","CLIME","CLING","CLINK","CLOAK","CLOCK","CLOMP","CLONE","CLOSE","CLOTH","CLOUD","CLOUT","CLOVE","CLOWN","CLUCK","CLUMP","CLUNK","COACH","COAST","COBOL","COBRA","COCCI","COCKY","COCOA","CODER","CODEX","COLIC","COLON","COLOR","COMBO","COMER","COMET","COMFY","COMIC","COMMA","CONCH","CONDO","CONGA","CONIC","COPRA","COPSE","CORAL","CORDS","CORER","CORGI","CORNY","CORPS","COSTS","COUCH","COUGH","COUNT","COUPE","COURT","COVEN","COVER","COVET","COVEY","COWER","COYLY","COYPU","COZEN","CRABS","CRACK","CRAFT","CRAMP","CRANE","CRANK","CRAPE","CRASH","CRASS","CRATE","CRAVE","CRAWL","CRAZE","CRAZY","CREAK","CREAM","CREDO","CREED","CREEK","CREEL","CREEP","CREPE","CRESS","CREST","CRICK","CRIER","CRIME","CRIMP","CRISP","CROAK","CROCK","CROFT","CRONE","CRONY","CROOK","CROON","CROSS","CROUP","CROWD","CROWN","CRUDE","CRUEL","CRUET","CRUMB","CRUSE","CRUSH","CRUST","CRYPT","CUBIC","CUBIT","CUMIN","CUPID","CUPPA","CURED","CURIE","CURIO","CURLY","CURRY","CURSE","CURVE","CURVY","CUSHY","CYCLE","CYDER","CYNIC","DACHA","DADDY","DAILY","DAIRY","DAISY","DALLY","DANCE","DANDY","DARTS","DATED","DATUM","DAUNT","DAVIT","DAZED","DEARY","DEATH","DEBAR","DEBIT","DEBUG","DEBUT","DECAF","DECAL","DECAY","DECOR","DECOY","DECRY","DEEDS","DEFER","DEGAS","DEIFY","DEIGN","DEISM","DEIST","DEITY","DELAY","DELFT","DELTA","DELVE","DEMOB","DEMON","DEMUR","DENIM","DENSE","DEPOT","DEPTH","DERBY","DETER","DETOX","DEUCE","DEVIL","DHOTI","DIARY","DICEY","DIGIT","DIMER","DIMLY","DINAR","DINER","DINGO","DINGY","DINKY","DIODE","DIRGE","DIRTY","DISCO","DISHY","DITCH","DITTO","DITTY","DIVAN","DIVER","DIVOT","DIVVY","DIZZY","DODGE","DODGY","DOGGY","DOGIE","DOGMA","DOILY","DOING","DOLLY","DOLOR","DOMED","DONOR","DOPED","DOPEY","DOSED","DOTTY","DOUBT","DOUGH","DOUSE","DOWDY","DOWEL","DOWER","DOWNY","DOWRY","DOWSE","DOYEN","DOZEN","DRAFT","DRAIN","DRAKE","DRAMA","DRAPE","DRAWL","DRAWN","DREAD","DREAM","DREAR","DREGS","DRESS","DRIED","DRIER","DRIFT","DRILL","DRINK","DRIVE","DROLL","DRONE","DROOL","DROOP","DROSS","DROVE","DROWN","DRUNK","DRUPE","DRYAD","DRYER","DRYLY","DUCAL","DUCAT","DUCHY","DUCKY","DULLY","DUMMY","DUMPS","DUMPY","DUPLE","DURUM","DUSKY","DUSTY","DUVET","DWARF","DWEEB","DWELL","DYING","EAGER","EAGLE","EARED","EARLY","EARTH","EASED","EASEL","EATER","EAVES","EBONY","ECLAT","EDEMA","EDGED","EDGER","EDICT","EDIFY","EDUCE","EERIE","EGRET","EIDER","EIGHT","EJECT","ELAND","ELATE","ELBOW","ELDER","ELECT","ELEGY","ELFIN","ELIDE","ELITE","ELOPE","ELUDE","ELVER","ELVES","EMAIL","EMBED","EMBER","EMCEE","EMEND","EMERY","EMOTE","EMPTY","ENACT","ENDED","ENDOW","ENDUE","ENEMA","ENEMY","ENJOY","ENNUI","ENSUE","ENTER","ENTRY","ENVOY","EPOCH","EPOXY","EQUAL","EQUIP","ERASE","ERECT","ERGOT","ERODE","ERROR","ERUPT","ESSAY","ESTER","ETHER","ETHIC","ETHOS","ETHYL","ETUDE","EVADE","EVENT","EVERY","EVICT","EVOKE","EXACT","EXALT","EXCEL","EXERT","EXILE","EXIST","EXPAT","EXPEL","EXTOL","EXTRA","EXUDE","EXULT","FABLE","FACED","FACET","FADDY","FADED","FAINT","FAIRY","FAITH","FAKER","FAKIR","FALLS","FALSE","FAMED","FANCY","FARAD","FARCE","FATAL","FATED","FATTY","FATWA","FAULT","FAUNA","FAVOR","FAZED","FEAST","FECAL","FECES","FEIGN","FEINT","FELLA","FELON","FEMUR","FENCE","FERAL","FERNY","FERRY","FETAL","FETCH","FETID","FETUS","FEVER","FEWER","FIBER","FICHU","FIELD","FIEND","FIERY","FIFTH","FIFTY","FIGHT","FILCH","FILER","FILLY","FILMY","FILTH","FINAL","FINCH","FINER","FINIS","FIRED","FIRST","FIRTH","FISHY","FITLY","FIVER","FIVES","FIXED","FIXER","FIZZY","FJORD","FLACK","FLAIL","FLAIR","FLAKE","FLAKY","FLAME","FLANK","FLAPS","FLARE","FLASH","FLASK","FLATS","FLECK","FLEET","FLESH","FLICK","FLIER","FLIES","FLING","FLINT","FLIRT","FLOAT","FLOCK","FLOOD","FLOOR","FLORA","FLOSS","FLOUR","FLOUT","FLUFF","FLUID","FLUKE","FLUKY","FLUME","FLUNK","FLUSH","FLUTE","FOAMY","FOCAL","FOCUS","FOGGY","FOIST","FOLIO","FOLKS","FOLLY","FORAY","FORCE","FORGE","FORGO","FORTE","FORTH","FORTY","FORUM","FOUND","FOUNT","FOYER","FRAIL","FRAME","FRANC","FRANK","FRAUD","FREAK","FRESH","FRIAR","FRIED","FRIES","FRILL","FRISK","FRIZZ","FROCK","FROND","FRONT","FROST","FROTH","FROWN","FRUIT","FRUMP","FRYER","FUDGE","FUGAL","FUGUE","FULLY","FUMED","FUMES","FUNDS","FUNKY","FUNNY","FUROR","FURRY","FURZE","FUSED","FUSEE","FUSSY","FUSTY","FUTON","FUZZY","GABBY","GABLE","GAFFE","GAILY","GAMIN","GAMMA","GAMMY","GAMUT","GASSY","GATOR","GAUDY","GAUNT","GAUZE","GAUZY","GAVEL","GAWKY","GECKO","GELID","GENIE","GENRE","GENUS","GEODE","GETUP","GHOST","GHOUL","GIANT","GIDDY","GIMPY","GIRTH","GIVEN","GIVER","GLACE","GLADE","GLAND","GLANS","GLARE","GLASS","GLAZE","GLEAM","GLEAN","GLIDE","GLINT","GLITZ","GLOAT","GLOBE","GLOOM","GLORY","GLOSS","GLOVE","GLUED","GLUEY","GLUON","GLYPH","GNARL","GNASH","GNOME","GODLY","GOFER","GOING","GOLLY","GONER","GOODY","GOOEY","GOOFY","GOOSE","GORGE","GORSE","GOUGE","GOURD","GOUTY","GRACE","GRADE","GRAFT","GRAIL","GRAIN","GRAND","GRANT","GRAPE","GRAPH","GRASP","GRASS","GRATE","GRAVE","GRAVY","GRAZE","GREAT","GREBE","GREED","GREEN","GREET","GRIEF","GRILL","GRIME","GRIMY","GRIND","GRIPE","GRIST","GRITS","GROAN","GROAT","GROIN","GROOM","GROPE","GROSS","GROUP","GROUT","GROVE","GROWL","GROWN","GRUEL","GRUFF","GRUMP","GRUNT","GUANO","GUARD","GUAVA","GUESS","GUEST","GUIDE","GUILD","GUILE","GUILT","GUISE","GULAG","GULCH","GULLY","GUMBO","GUMMY","GUNNY","GUPPY","GUSHY","GUSTO","GUSTY","GUTSY","GYPSY","HABIT","HAIKU","HAIRY","HALAL","HALLO","HALON","HALVE","HAMMY","HANDS","HANDY","HAPLY","HAPPY","HARDY","HAREM","HARPY","HARRY","HARSH","HASTE","HASTY","HATCH","HATED","HATER","HAUNT","HAVEN","HAVOC","HAZEL","HEADS","HEADY","HEAPS","HEARD","HEART","HEATH","HEAVE","HEAVY","HEDGE","HEFTY","HEIST","HELIX","HELLO","HELOT","HELVE","HENCE","HENNA","HERON","HERTZ","HEWER","HEXED","HIKER","HILLY","HINGE","HIPPO","HIRED","HIRER","HITCH","HIVES","HOARD","HOARY","HOBBY","HOGAN","HOIST","HOKEY","HOKUM","HOLEY","HOLLY","HOMER","HOMEY","HONEY","HONOR","HOOCH","HOOEY","HOOKS","HOOKY","HOOPS","HORDE","HORSE","HOTEL","HOTLY","HOUND","HOURI","HOURS","HOUSE","HOVEL","HOVER","HOWDY","HUBBY","HUFFY","HULLO","HUMAN","HUMID","HUMOR","HUMPH","HUMUS","HUNCH","HURRY","HUSKY","HUTCH","HYDRA","HYENA","HYMEN","ICILY","ICING","ICTUS","IDEAL","IDIOM","IDLER","IDYLL","IGLOO","ILEUM","ILIUM","IMAGE","IMAGO","IMBUE","IMPEL","IMPLY","INANE","INAPT","INCUR","INDEX","INDIE","INEPT","INERT","INFER","INFIX","INFRA","INGOT","INLAY","INLET","INNER","INPUT","INSET","INTER","INURE","IONIC","IRATE","IRONS","IRONY","ISLET","ISSUE","ITCHY","IVIED","IVORY","JABOT","JACKS","JADED","JAPAN","JAUNT","JAWED","JAZZY","JELLY","JEMMY","JENNY","JERKY","JETTY","JEWEL","JIFFY","JIHAD","JIMMY","JINGO","JINKS","JOINT","JOIST","JOKER","JOLLY","JOULE","JOUST","JOWLY","JUDGE","JUICE","JUICY","JULEP","JUMBO","JUMPY","JUNCO","JUNTA","JUROR","KABOB","KAPOK","KAPPA","KAPUT","KARAT","KARMA","KAYAK","KAZOO","KEBAB","KETCH","KEYED","KHAKI","KINDA","KIOSK","KITTY","KLUTZ","KNACK","KNAVE","KNEAD","KNEEL","KNELL","KNIFE","KNISH","KNOCK","KNOLL","KNOWN","KOALA","KOOKY","KRAAL","KRILL","KRONA","KRONE","KUDOS","KUDZU","LABEL","LABOR","LACED","LADEN","LADLE","LAGER","LAIRD","LAITY","LANAI","LANCE","LANKY","LAPEL","LAPIN","LAPSE","LARCH","LARGE","LARGO","LARVA","LASER","LASSO","LATCH","LATER","LATEX","LATHE","LATTE","LAUGH","LAXLY","LAYER","LAYUP","LEACH","LEAFY","LEAKY","LEARN","LEASE","LEASH","LEAST","LEAVE","LEDGE","LEECH","LEERY","LEFTY","LEGAL","LEGGY","LEMMA","LEMON","LEMUR","LENTO","LEPER","LETCH","LETUP","LEVEE","LEVEL","LEVER","LEXIS","LIBEL","LICIT","LIEGE","LIFER","LIGHT","LIKED","LIKEN","LILAC","LIMBO","LIMEY","LIMIT","LINED","LINEN","LINER","LINGO","LINKS","LIPID","LISLE","LITER","LITHE","LIVEN","LIVER","LIVID","LLAMA","LLANO","LOADS","LOAMY","LOATH","LOBAR","LOBBY","LOBED","LOCAL","LOCUM","LOCUS","LODGE","LOFTY","LOGIC","LOINS","LOLLY","LONER","LOONY","LOOPY","LOOSE","LORRY","LOSER","LOTTO","LOTUS","LOUGH","LOUSE","LOUSY","LOVED","LOVER","LOWER","LOWLY","LOYAL","LUCID","LUCKY","LUCRE","LUMEN","LUMPY","LUNAR","LUNCH","LUNGE","LUPUS","LURCH","LURID","LUSTY","LYING","LYMPH","LYNCH","LYRIC","MACAW","MACHO","MACRO","MADAM","MADLY","MAFIA","MAGIC","MAGMA","MAIZE","MAJOR","MAKER","MAMBA","MAMBO","MANGE","MANGO","MANGY","MANIA","MANIC","MANLY","MANNA","MANOR","MANSE","MANTA","MAPLE","MARCH","MARGE","MARIA","MARRY","MARSH","MASER","MASON","MATCH","MATED","MATER","MATES","MATEY","MATTE","MATZO","MAUVE","MAVEN","MAXIM","MAYBE","MAYOR","MEALY","MEANS","MEATY","MECCA","MEDAL","MEDIC","MELEE","MELON","MERCY","MERGE","MERIT","MERRY","MESON","MESSY","METAL","METER","METRO","MEZZO","MICRO","MIDDY","MIDGE","MIDST","MIGHT","MILCH","MILER","MILKY","MIMIC","MINCE","MINED","MINER","MINGY","MINIM","MINOR","MINTY","MINUS","MIRED","MIRTH","MISER","MISTY","MITER","MIXED","MIXER","MOCHA","MODAL","MODEL","MODEM","MOGUL","MOIRE","MOIST","MOLAR","MOLDY","MOLLY","MOMMA","MOMMY","MONEY","MONTH","MOOCH","MOODY","MOOSE","MOPED","MOPES","MORAL","MORAY","MOREL","MORES","MOSEY","MOSSY","MOTEL","MOTET","MOTIF","MOTOR","MOTTO","MOULT","MOUND","MOUNT","MOURN","MOUSE","MOUSY","MOUTH","MOVED","MOVER","MOVIE","MOWER","MOXIE","MUCKY","MUCUS","MUDDY","MUFTI","MUGGY","MULCH","MULCT","MUMMY","MUMPS","MUNCH","MURAL","MURKY","MUSHY","MUSIC","MUSKY","MUSSY","MUSTY","MUTED","MYRRH","NABOB","NACHO","NACRE","NADIR","NAIAD","NAIVE","NAKED","NAMES","NANNY","NAPPY","NASAL","NASTY","NATAL","NATTY","NAVAL","NAVEL","NAVVY","NEATH","NEEDS","NEEDY","NEIGH","NERVE","NERVY","NEVER","NEVUS","NEWEL","NEWLY","NEWSY","NEXUS","NICHE","NIECE","NIFTY","NIGHT","NINJA","NINNY","NINTH","NIPPY","NITER","NOBLE","NOBLY","NOHOW","NOISE","NOISY","NOMAD","NONCE","NOOSE","NORTH","NOSED","NOTCH","NOTED","NOVEL","NUBBY","NUDGE","NURSE","NUTTY","NYLON","NYMPH","OAKEN","OAKUM","OASIS","OATEN","OBESE","OCCUR","OCEAN","OCHER","OCTAL","OCTET","ODDLY","ODIUM","OFFAL","OFFER","OFTEN","OHMIC","OILED","OKAPI","OLDEN","OLDER","OLDIE","OLIVE","OMEGA","ONION","ONSET","OOMPH","OPERA","OPINE","OPIUM","OPTIC","ORATE","ORBIT","ORDER","ORGAN","ORIEL","ORRIS","OSIER","OTHER","OTTER","OUNCE","OUTDO","OUTER","OUTGO","OUTRE","OVARY","OVATE","OVERT","OVOID","OVULE","OWING","OWLET","OWNED","OWNER","OXBOW","OXIDE","OZONE","PACER","PADRE","PAEAN","PAGAN","PAGER","PAINS","PAINT","PALLY","PALMY","PALSY","PANDA","PANEL","PANIC","PANTO","PANTS","PAPAL","PAPAW","PAPER","PARCH","PARER","PARKA","PARRY","PARSE","PARTS","PARTY","PASHA","PASSE","PASTA","PASTE","PASTY","PATCH","PATER","PATIO","PATSY","PATTY","PAUSE","PAVED","PAYEE","PAYER","PEACE","PEACH","PEAKY","PEARL","PEATY","PECAN","PEDAL","PEEVE","PEKOE","PENAL","PENNY","PEONY","PEPPY","PERCH","PERIL","PERKY","PERRY","PESKY","PESTO","PETAL","PETER","PETTY","PEWEE","PHAGE","PHASE","PHIAL","PHLOX","PHONE","PHONY","PHOTO","PIANO","PICKY","PICOT","PIECE","PIETY","PIGGY","PILAF","PILES","PILOT","PINCH","PINKO","PINNY","PINON","PINTO","PIOUS","PIPER","PIPIT","PIQUE","PISTE","PITCH","PITHY","PITON","PITTA","PIVOT","PIXEL","PIXIE","PIZZA","PLACE","PLAID","PLAIN","PLAIT","PLANE","PLANK","PLANT","PLASH","PLATE","PLATY","PLAZA","PLEAD","PLEAT","PLEBE","PLONK","PLUCK","PLUMB","PLUME","PLUMP","PLUMY","PLUNK","PLUSH","POACH","POESY","POINT","POISE","POKER","POLAR","POLIO","POLKA","POLLS","POLYP","POOCH","POPPY","PORCH","PORGY","POSED","POSER","POSIT","POSSE","POTTY","POUCH","POUND","POWER","PRANG","PRANK","PRATE","PRAWN","PREEN","PRESS","PRICE","PRIDE","PRIME","PRIMP","PRINT","PRION","PRIOR","PRISM","PRIVY","PRIZE","PROBE","PROLE","PRONE","PRONG","PROOF","PROPS","PROSE","PROSY","PROUD","PROVE","PROWL","PROXY","PRUDE","PRUNE","PSALM","PSHAW","PUBES","PUBIC","PUBIS","PUDGY","PUFFY","PUKKA","PULPY","PULSE","PUNCH","PUNKS","PUPAL","PUPIL","PUPPY","PUREE","PURGE","PURSE","PUSHY","PUTTY","PYGMY","PYLON","QUACK","QUAFF","QUAIL","QUAKE","QUALM","QUARK","QUART","QUASH","QUASI","QUEEN","QUEER","QUELL","QUERN","QUERY","QUEST","QUEUE","QUICK","QUIET","QUIFF","QUILL","QUILT","QUINT","QUIRE","QUIRK","QUIRT","QUITE","QUITS","QUOIN","QUOIT","QUOTA","QUOTE","RABBI","RABID","RACER","RADAR","RADIO","RADIX","RADON","RAFTS","RAILS","RAINY","RAISE","RAJAH","RALLY","RAMIE","RANCH","RANEE","RANGE","RANGY","RAPID","RASPY","RATES","RATIO","RATTY","RAVEL","RAVEN","RAVER","RAYON","RAZED","RAZOR","REACH","REACT","READY","REALM","REARM","REBEL","REBUS","REBUT","RECAP","RECCE","RECTO","RECUR","REEDY","REEVE","REFER","REFIT","REGAL","REIGN","RELAX","RELAY","RELIC","REMIT","RENAL","RENEW","REPAY","REPEL","REPLY","RERUN","RESET","RESIN","RETCH","RETIE","RETRO","RETRY","REUSE","REVEL","REVUE","RHEUM","RHINO","RHYME","RICER","RIDER","RIDGE","RIFLE","RIGHT","RIGID","RIGOR","RILED","RIMED","RINGS","RINSE","RIPEN","RISEN","RISER","RISKY","RITZY","RIVAL","RIVER","RIVET","RIYAL","ROACH","ROADS","ROAST","ROBED","ROBIN","ROBOT","ROCKY","RODEO","ROGUE","ROMAN","RONDO","ROOMS","ROOMY","ROOST","ROOTS","ROPER","ROPEY","ROSIN","ROTOR","ROUGE","ROUGH","ROUND","ROUSE","ROUTE","ROVER","ROWAN","ROWDY","ROWEL","ROWER","ROYAL","RUBLE","RUDDY","RUGBY","RULED","RULER","RUMBA","RUMMY","RUMOR","RUNIC","RUNNY","RUNTY","RUPEE","RURAL","RUSHY","RUSTY","RUTTY","SABER","SABLE","SABOT","SABRA","SADHU","SADLY","SAHIB","SAINT","SALAD","SALES","SALLY","SALON","SALSA","SALTY","SALVE","SALVO","SAMBA","SANDS","SANDY","SAPPY","SARAN","SASSY","SATIN","SATYR","SAUCE","SAUCY","SAUNA","SAUTE","SAVED","SAVER","SAVOR","SAVOY","SAVVY","SCADS","SCALD","SCALE","SCALP","SCALY","SCAMP","SCANT","SCAPE","SCARE","SCARF","SCARP","SCARY","SCENE","SCENT","SCHWA","SCION","SCOFF","SCOLD","SCONE","SCOOP","SCOOT","SCOPE","SCORE","SCORN","SCOUR","SCOUT","SCOWL","SCRAG","SCRAM","SCRAP","SCREE","SCREW","SCRIM","SCRIP","SCROD","SCRUB","SCRUM","SCUBA","SCUFF","SCULL","SCURF","SEAMY","SEATS","SEBUM","SEDAN","SEDGE","SEDGY","SEEDY","SEEMS","SEGUE","SEINE","SEIZE","SENNA","SENSE","SEPAL","SEPIA","SERGE","SERIF","SERUM","SERVE","SERVO","SETUP","SEVEN","SEVER","SEWED","SEWER","SHACK","SHADE","SHADY","SHAFT","SHAKE","SHAKY","SHALE","SHAME","SHANK","SHAPE","SHARD","SHARE","SHARK","SHARP","SHAVE","SHAWL","SHEAF","SHEAR","SHEEN","SHEEP","SHEER","SHEET","SHEIK","SHELF","SHELL","SHIFT","SHILL","SHINE","SHINY","SHIRE","SHIRK","SHIRT","SHOAL","SHOAT","SHOCK","SHOES","SHOOK","SHOOT","SHORE","SHORT","SHOUT","SHOVE","SHOWY","SHRED","SHREW","SHRUB","SHRUG","SHUCK","SHUNT","SHUSH","SHYLY","SIBYL","SIDLE","SIEGE","SIEVE","SIGHT","SIGMA","SILKS","SILKY","SILLY","SILTY","SINCE","SINEW","SINGE","SINUS","SIREN","SISAL","SITAR","SIXTH","SIXTY","SIZED","SKATE","SKEET","SKEIN","SKIER","SKIFF","SKILL","SKIMP","SKINT","SKIRT","SKIVE","SKULK","SKULL","SKUNK","SLACK","SLAIN","SLAKE","SLANG","SLANT","SLASH","SLATE","SLAVE","SLEEK","SLEEP","SLEET","SLEWS","SLICE","SLICK","SLIDE","SLIME","SLIMY","SLING","SLINK","SLOOP","SLOPE","SLOPS","SLOSH","SLOTH","SLUMP","SLURP","SLUSH","SLYLY","SMACK","SMALL","SMART","SMASH","SMEAR","SMELL","SMELT","SMILE","SMIRK","SMITE","SMITH","SMOCK","SMOKE","SMOKY","SNACK","SNAFU","SNAIL","SNAKE","SNAKY","SNARE","SNARL","SNEAK","SNEER","SNICK","SNIDE","SNIFF","SNIPE","SNIPS","SNOOD","SNOOP","SNOOT","SNORE","SNORT","SNOUT","SNOWY","SNUFF","SOAPY","SOBER","SOFTY","SOGGY","SOLAR","SOLED","SOLID","SOLVE","SONAR","SONIC","SONNY","SOOTH","SOOTY","SOPPY","SORRY","SOUGH","SOUND","SOUPY","SOUSE","SOUTH","SOWER","SPACE","SPADE","SPANK","SPARE","SPARK","SPASM","SPATE","SPAWN","SPEAK","SPEAR","SPECK","SPECS","SPEED","SPELL","SPEND","SPENT","SPICE","SPICY","SPIEL","SPIFF","SPIKE","SPIKY","SPILL","SPINE","SPINY","SPIRE","SPITE","SPLAT","SPLAY","SPLIT","SPOIL","SPOKE","SPOOF","SPOOK","SPOOL","SPOON","SPOOR","SPORE","SPORT","SPOTS","SPOUT","SPRAT","SPRAY","SPREE","SPRIG","SPROG","SPUME","SPUNK","SPURN","SPURT","SQUAB","SQUAD","SQUAT","SQUIB","SQUID","STACK","STAFF","STAGE","STAGY","STAID","STAIN","STAIR","STAKE","STALE","STALK","STALL","STAMP","STAND","STAPH","STARE","STARK","START","STASH","STATE","STAVE","STAYS","STEAD","STEAK","STEAL","STEAM","STEED","STEEL","STEEP","STEER","STEIN","STEPS","STERN","STICK","STIFF","STILE","STILL","STILT","STING","STINK","STINT","STOAT","STOCK","STOGY","STOIC","STOKE","STOLE","STOMA","STOMP","STONE","STONY","STOOL","STOOP","STOPS","STORE","STORK","STORM","STORY","STOUP","STOUT","STOVE","STRAP","STRAW","STRAY","STREP","STREW","STRIA","STRIP","STROP","STRUM","STRUT","STUCK","STUDY","STUFF","STUMP","STUNG","STUNT","STYLE","SUAVE","SUCKS","SUDSY","SUEDE","SUGAR","SUITE","SULFA","SULKY","SULLY","SUMAC","SUNNY","SUNUP","SUPER","SUPRA","SURGE","SURLY","SUSHI","SWAIN","SWAMI","SWAMP","SWANK","SWARD","SWARM","SWASH","SWATH","SWEAR","SWEAT","SWEDE","SWEEP","SWEET","SWELL","SWEPT","SWIFT","SWILL","SWINE","SWING","SWIPE","SWIRL","SWISH","SWOON","SWOOP","SWORD","SWORN","SYLPH","SYNOD","SYRUP","TABBY","TABLE","TABOO","TABOR","TACIT","TACKY","TAFFY","TAILS","TAINT","TAKEN","TAKER","TALKS","TALKY","TALLY","TALON","TALUS","TAMED","TAMER","TANGO","TANGY","TANSY","TAPED","TAPER","TAPIR","TARDY","TAROT","TARRY","TASTE","TASTY","TATER","TATTY","TAUNT","TAUPE","TAWNY","TAXER","TAXIS","TEACH","TEARS","TEARY","TEASE","TEDDY","TEENS","TEENY","TEETH","TELEX","TELLY","TEMPO","TEMPT","TENCH","TENET","TENON","TENOR","TENSE","TENTH","TEPEE","TEPID","TERMS","TERRY","TERSE","TESTY","TETRA","THANE","THANK","THEFT","THEIR","THEME","THERE","THERM","THESE","THETA","THICK","THIEF","THIGH","THINE","THING","THINK","THIRD","THOLE","THONG","THORN","THOSE","THREE","THROB","THROE","THROW","THRUM","THUMB","THUMP","THYME","TIARA","TIBIA","TIDAL","TIGER","TIGHT","TILDE","TILED","TILER","TIMED","TIMER","TIMES","TIMID","TINGE","TINNY","TIPSY","TIRED","TITAN","TITER","TITHE","TITLE","TIZZY","TOADY","TOAST","TODAY","TODDY","TOKEN","TONAL","TONED","TONER","TONGS","TONIC","TONNE","TOOTH","TOPAZ","TOPEE","TOPIC","TOQUE","TORCH","TORSO","TORTE","TORUS","TOTAL","TOTEM","TOTER","TOUCH","TOUGH","TOWEL","TOWER","TOXIC","TOXIN","TRACE","TRACK","TRACT","TRADE","TRAIL","TRAIN","TRAIT","TRAMP","TRASH","TRAWL","TREAD","TREAT","TREED","TREND","TRESS","TREWS","TRIAD","TRIAL","TRIBE","TRICE","TRICK","TRIED","TRIER","TRIKE","TRILL","TRIPE","TRITE","TROLL","TROOP","TROPE","TROTH","TROUT","TROVE","TRUCE","TRUCK","TRULY","TRUMP","TRUNK","TRUSS","TRUST","TRUTH","TRYST","TUBAL","TUBBY","TUBED","TUBER","TULIP","TULLE","TUMID","TUMMY","TUMOR","TUNER","TUNIC","TUNNY","TURPS","TUTOR","TWAIN","TWANG","TWEAK","TWEED","TWEET","TWICE","TWILL","TWINE","TWINS","TWIRL","TWIST","TYING","UDDER","UKASE","ULCER","ULNAR","ULTRA","UMBEL","UMBER","UMBRA","UNBAR","UNCLE","UNCUT","UNDER","UNDUE","UNFED","UNFIT","UNIFY","UNION","UNITE","UNITY","UNLIT","UNMAN","UNPIN","UNSAY","UNTIE","UNTIL","UNWED","UNZIP","UPEND","UPPER","UPSET","URBAN","URINE","USAGE","USHER","USING","USUAL","USURP","USURY","UTTER","UVULA","VAGUE","VALET","VALID","VALOR","VALUE","VALVE","VAPID","VAPOR","VAULT","VAUNT","VEGAN","VELAR","VELUM","VENAL","VENOM","VENUE","VERGE","VERSE","VERSO","VERVE","VETCH","VEXED","VIAND","VIBES","VICAR","VIDEO","VIGIL","VIGOR","VILLA","VINYL","VIOLA","VIPER","VIRAL","VIREO","VIRUS","VISIT","VISOR","VISTA","VITAL","VIVID","VIXEN","VOCAL","VODKA","VOGUE","VOICE","VOILE","VOMIT","VOTER","VOUCH","VOWEL","WACKO","WACKY","WADER","WAFER","WAGER","WAGES","WAGON","WAIST","WAIVE","WAKEN","WALLY","WALTZ","WANLY","WARTY","WASHY","WASTE","WATCH","WATER","WAVER","WAXED","WAXEN","WEARY","WEAVE","WEDGE","WEEDS","WEEDY","WEENY","WEEPY","WEIGH","WEIRD","WELSH","WHACK","WHALE","WHARF","WHEAL","WHEAT","WHEEL","WHELK","WHELM","WHELP","WHERE","WHICH","WHIFF","WHILE","WHINE","WHINY","WHIRL","WHISK","WHIST","WHITE","WHOLE","WHOOP","WHORL","WHOSE","WHOSO","WIDEN","WIDOW","WIDTH","WIELD","WIGHT","WIMPY","WINCE","WINCH","WINDY","WINGS","WIPER","WIRED","WISPY","WITCH","WITHE","WITTY","WOMAN","WONKY","WOODS","WOODY","WOOER","WOOZY","WORDS","WORDY","WORKS","WORLD","WORMY","WORRY","WORSE","WORST","WORTH","WOUND","WOVEN","WRACK","WRATH","WREAK","WRECK","WREST","WRING","WRIST","WRITE","WRONG","WROTH","WRYLY","XENON","XEROX","XYLEM","YACHT","YAHOO","YEARN","YEARS","YEAST","YIELD","YODEL","YOGIC","YOKEL","YOUNG","YOURS","YOUTH","YUCCA","YUCKY","YUMMY","ZEBRA","ZESTY","ZILCH","ZIPPY","ZLOTY","ZONAL"};
string user;
string base="\\.wordle\\data.wd";
int back=FOREGROUND_INTENSITY|FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_GREEN;
int red=FOREGROUND_INTENSITY|FOREGROUND_RED;
int green=FOREGROUND_INTENSITY|FOREGROUND_GREEN;
int blue=FOREGROUND_INTENSITY|FOREGROUND_BLUE;
int yellow=FOREGROUND_INTENSITY|FOREGROUND_GREEN|FOREGROUND_RED;
void scta(int clr){
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),clr);
}
vector<pair<char,int> > hist[10010];
int cnt[26];
int col[10010];
void wordle(){
	int id=rand()%(int)(words.size());
	scta(back);
	int round=0;
	while(1){
		round++;
		if(round==10000){
			scta(red);
			cout<<"GAME OVER!"<<endl;
			scta(green);
			cout<<"ANSWER: "<<words[id]<<endl;
			scta(back);
			system("pause");
			return;
		}
		system("cls");
		scta(back);
		printf("Try #%4d\n",round);
		cout<<(int)(words[id].size())<<" letters."<<endl;
		for(int i=0;i<(int)(words[id].size());i++) cout<<"_";
		cout<<endl;
		hist[round].clear();
		for(int i=1;i<round;i++){
			for(int j=0;j<hist[i].size();j++){
				scta(hist[i][j].second);
				cout<<hist[i][j].first;
			}
			cout<<endl;
		}
		scta(back);
		string ssss;
		cin>>ssss;
		if((int)(ssss.size())!=(int)(words[id].size())){
    		for(int i=0;i<(int)(ssss.size());i++)
				hist[round].push_back(make_pair(ssss[i],blue));
			continue;
		}
		memset(cnt,0,sizeof(cnt));
		for(int i=0;i<(int)(words[id].size());i++) cnt[words[id][i]-'a']++;
		int GR=0;
		for(int i=0;i<(int)(words[id].size());i++){
			if(ssss[i]==words[id][i]){
				cnt[ssss[i]-'a']--;
				col[i]=green;
				ssss[i]=ssss[i]-'a'+'A';
				GR++;
			}
		}
		for(int i=0;i<(int)(words[id].size());i++){
			if(ssss[i]>='a'&&cnt[ssss[i]-'a']){
				cnt[ssss[i]-'a']--;
				col[i]=yellow;
				ssss[i]=ssss[i]-'a'+'A';
			}
		}
		for(int i=0;i<(int)(words[id].size());i++){
			if(ssss[i]>='a'){
				col[i]=red;
				ssss[i]=ssss[i]-'a'+'A';
			}
		}
    	for(int i=0;i<(int)(words[id].size());i++)
			hist[round].push_back(make_pair(ssss[i]-'A'+'a',col[i]));
		if(GR==(int)(words[id].size())){
			system("cls");
			printf("Try #%4d\n",round);
			cout<<(int)(words[id].size())<<" letters."<<endl;
			for(int i=0;i<(int)(words[id].size());i++) cout<<"_";
			cout<<endl;
			for(int i=1;i<=round;i++){
				for(int j=0;j<hist[i].size();j++){
					scta(hist[i][j].second);
					cout<<hist[i][j].first;
				}
				cout<<endl;
			}
			scta(back);
			printf("Guessed correctly after %d tries.\n",round);
			scta(back);
			system("pause");
			return;
		}
	}
}
int main(){
	for(int i=0;i<(int)(words.size());i++) for(int j=0;j<words[i].size();j++)
		words[i][j]-='A',words[i][j]+='a';
	system("cls");
	system("date /t > curtimewd.txt");
	ifstream tfin("curtimewd.txt");
	string tim;tfin>>tim;
	tfin.close();system("del curtimewd.txt");
	string ntim=tim.substr(0,4)+tim.substr(5,2)+tim.substr(8,2);
	tim=ntim;
	if(ntim>expire){
		scta(red);
		cout<<"WARNING:This version of wordle is no longer supported."<<endl;
		cout<<"        It's suggested to download a newer version and replace this one."<<endl;
		scta(back);
		system("pause");
		system("cls");
	}
	scta(back);
	srand(unsigned(time(NULL)));
	while(1){
		system("cls");
		cout<<"WORDLE (C++) Version "<<ver<<" "<<type<<" ("<<date<<") by David X"<<endl;
		cout<<"0)   exit"<<endl;
		cout<<"1)   play wordle"<<endl;
		cout<<"Please choose one (index):"<<flush;
		int t=getch();
		cout<<(char)(t)<<endl;
		if(t=='0') return 0;
		if(t=='1') wordle();
	}
	return 0;
}

